#!/bin/bash
#
# LoungeMC - A content centered media center 
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#


. /lounge/bin/initcgi "text/html"

notify "Loading web page: $@" 3
./reset
./removeoverlay
export MOZ_PLUGIN_PATH="/usr/lib/flashplugin-nonfree/"

[ -z "$QUERY_STRING" ] && QUERY_STRING="$@";
pid=`ps -ef | grep "midori.*class=Browser" | fgrep -v grep | tr -s " " | cut -d" " -f2`
if [ -n "$pid" ]; then 
	midori --class="Browser" --name="Browser" -e TabCloseOther 
fi
pid=`ps -ef | grep "midori.*class=Browser" | fgrep -v grep | tr -s " " | cut -d" " -f2`
[ -n "$pid" ] && kill -9 $pid

midori --class="Browser" --name="Browser" "$QUERY_STRING" &> /dev/null
