#!/bin/bash
#
# LoungeMC - A content centered media center 
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#



. /lounge/bin/initcgi "text/html"
./reset
./removeoverlay

set -x
[ -z "$QUERY_STRING" ] && QUERY_STRING="$@"
notify "Loading image: `basename "$QUERY_STRING"`"
tmpimg=`mktemp`
wget --no-check-certificate -O "$tmpimg" "$QUERY_STRING"
feh -F --image-bg black --auto-zoom "$tmpimg" &
bash -c "sleep 60; rm $tmpimg"
disown
exit 0
