#!/bin/bash
#
# LoungeMC - A content centered media center 
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#



. /lounge/bin/initcgi "text/plain"

LIST="/var/run/player/playlist"
TITLES="/var/run/player/playlist_titles"
CACHE="/var/run/player/playlist_cache"

set -x
(
  flock -x 200

  if [ ! -f $CACHE || ! -f $LIST ]; then
    touch $CACHE
    touch $LIST
  fi
  mod_p="`stat -c %Y $LIST`"
  mod_c="`stat -c %Y $CACHE`"

  if [ $mod_p -gt $mod_c ]; then
    if [ ! -s $LIST ]; then
      echo "<span style=\"color: lightgrey; font-weight: bold;\">(playlist empty)</span>" > "$CACHE"
    else
      (
      echo "<div>"
      i=0
      cat "$TITLES" | while read line; do
        title="`echo $line | sed -e 's/\([A-Z]\)/ \1/g' -e 's/^ \([a-z]\)/\1/g'`"
        title=${title:0:70}
        item="`sed "$[$i+1]!d" /var/run/player/playlist`"
  	idx="`cat /var/run/player/playlist_idx`"
        current="`cat /var/run/player/currentpath`"
        color="white"
        bgcolor="#555"
        id="$i"
	
        [ $[ $i % 2  ] -eq 0 ] && bgcolor="#777"
        if [ "$i" -eq "$idx" ]; then 
	  color="orange"
	  id="currentitem"
	fi
        echo "<div id=\"$id\" onclick=\"$.get('cgi-bin/playlist_jump?$i');\" style=\"padding: 2px;text-align:left; width: 100%; cursor: pointer; background-color: $bgcolor; color: $color;  border: 1px outset $bgcolor; \">$title</div>"
        i=$[ $i + 1 ]
      done
      echo "</div>"
      ) > "$CACHE"
    fi
  fi

  cat "$CACHE"
) 200> /var/run/player/playlist_lock 2>/tmp/playlist
