#!/bin/bash
#
# LoungeMC - A content centered media center 
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#



. /lounge/bin/initcgi "text/plain"

i=0

if [ ! -s /var/run/player/playlist ]; then
  echo "<span style=\"color: lightgrey; font-weight: bold;\">(playlist empty)</span>"
fi

cat /var/run/player/playlist_titles | while read line; do
  item="`sed "$[$i+1]!d" /var/run/player/playlist`"
  current="`cat /var/run/player/currentpath`"
  color="white"
  [ "$item" == "$current" ] && color="orange"
  echo "<a style=\"color: $color;\" href=\"javascript:(function(){$.get('cgi-bin/playlist_jump?$i');})()\">$line</a></br>"
  i=$[ $i + 1 ]
done


