#!/bin/bash
#
# ScreenInvader - A shared media experience. Instant and seamless.
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#



. /lounge/bin/initcgi "text/html"

cat <<- eohtml
	<html>
	<head>
	<title></title>
	</head>
	<body style="background-color: #000000; vertical-align: middle">
		<pre style="vertical-align: middle; width: 100px; border:1px solid white; margin-left: auto; margin-right: auto; text-align:center; color: #ffffff; font-size:100%; font-weight: bold; font-family: 'Lucida Console', Monaco, monospace;"><b style="padding: 100px;">$1</b></pre>
	</body>
	</html>
eohtml
