#!/bin/bash
#
# LoungeMC - A content centered media center 
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#



url=$1
client_id="2dcf4e12afd6ed5119741f888260fc85"
resolve="http://api.soundcloud.com/resolve.json?url=$url&client_id=$client_id"
stream=`curl -v -L -o - "$resolve" | grep -Po '"stream_url":.*?[^\\\]",' | cut -d"\"" -f4`
json=`curl -v -L -o - "$resolve"`
#echo $json | sed 's/,/,\n/g' | sed '1,/"kind":"track"/d' | fgrep '"title":' | cut -d"\"" -f4- | sed 's/\\"/\"/g' | sed 's/\",$//'
for s in $stream; do
echo  mpc add "${s}?client_id=${client_id}"
done
mpc play
#/var/www/cge-bin/show "$stream?$client_id"
