#!/bin/bash
set -x
. /lounge/bin/initcgi "text/html"

./reset

/var/www/bin/notify "loading soup..." 1

echo "$QUERY_STRING"
[ -z "$QUERY_STRING" ] && QUERY_STRING="$@"

function getImage() {
  echo "$1" | fgrep "click to zoom" | sed 's/^.*href="//g' | sed 's/".*$//g'
}

function getVimeo() {
  ID="`echo "$1" | grep "<embed.*vimeo.com" | sed 's/^.*clip_id=//g'  | sed 's/&.*$//g'`"
  [ -n "$ID" ] && echo "http://vimeo.com/$ID"
}

function getYoutube() {
  URL="`echo "$1" | grep "<embed.*youtube.com" | sed 's/^.*embed src="//g'  | sed 's/".*$//g'`"
  [ -n "$URL" ] && echo "$URL"
}

PAGE="`wget -q -O - "$QUERY_STRING"`"
IMAGE="`getImage "$PAGE"`"
VIMEO="`getVimeo "$PAGE"`"
YOUTUBE="`getYoutube "$PAGE"`"


[ -n "$IMAGE" ] && QUERY_STRING="$IMAGE" ./image "$IMAGE"
[ -n "$VIMEO" ] && QUERY_STRING="$VIMEO" ./youtube "$VIMEO"
[ -n "$YOUTUBE" ] && QUERY_STRING="$YOUTUBE" ./youtube "$YOUTUBE"

