#!/bin/bash

. /lounge/bin/initcgi "text/plain"

[ "`./isUpdating | sed '1,2d'`" == "true" ] && exit 0;

(
  /usr/local/bin/updatemovie
  /usr/local/bin/updateimage
#  /usr/local/bin/updatemusic
  mpc update
) > /dev/null &
disown


