#!/bin/bash
#
# LoungeMC - A content centered media center 
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#



set -x
. /lounge/bin/initcgi "text/html"

./reset

notify "loading youtube..." 1

[ -z "$QUERY_STRING" ] && QUERY_STRING="$@"

(
function getCliveCSV() {
  /usr/bin/clive -f mp4 --filename-format="%t" --emit-csv "$1" | grep "^csv:"
}

function playVideoFromCSV() {
  TITLE="`echo "$1" | cut -d'"' -f2`"
  URL="`echo "$1" | cut -d'"' -f6`"
  notify "playing: $TITLE"
#  addToHistory
  player loadVideo "$URL" "$TITLE"
  disown
}

CSV="`getCliveCSV "$QUERY_STRING"`"

function play() {
CSV="`getCliveCSV "$1"`"

if [ -n "$CSV" ]; then
  playVideoFromCSV "$CSV"
else
  notify "failed"
fi

}

#if [ -n "`echo "$QUERY_STRING" | fgrep "list="`" ]; then
#  notify "loading youtube playlist.." 8
#  urls="`clivescan -an "$QUERY_STRING" | grep "^fetch" | awk '{ print $2 }'`" 
#  playB "`echo $urls | sed 's/ /\n/g' | sed '1d'`"
#else
 play "$QUERY_STRING"
#fi
) &> /tmp/youtube
