#!/bin/bash

set -x
. /lounge/bin/initcgi "text/html"

./reset

notify "loading youtube..." 1

[ -z "$QUERY_STRING" ] && QUERY_STRING="$@"

(
function getCliveCSV() {
  /usr/bin/clive -f mp4 --filename-format="%t" --emit-csv "$1" | grep "^csv:"
}

function playVideoFromCSV() {
  TITLE="`echo "$1" | cut -d'"' -f2`"
  URL="`echo "$1" | cut -d'"' -f6`"
  notify "playing: $TITLE"
#  addToHistory
  mplayer.video "$URL"
  disown
}

function playVideoFromCSVB() {
  TITLE="`echo "$1" | cut -d'"' -f2`"
  URL="`echo "$1" | cut -d'"' -f6`"
  notify "playing: $TITLE"
#  addToHistory
  mplayer.block "$URL"
 [ $? != 0 ] && exit 1; 
}

CSV="`getCliveCSV "$QUERY_STRING"`"

function addToHistory() {
  HISTORY_FILE="/tmp/youtube-history"
  TMP_HISTORY=$HISTORY_FILE".tmp"
 
  if [ ! -f $HISTORY_FILE ];
  then
    touch $HISTORY_FILE
  fi 

  echo -e "<a href=\"$QUERY_STRING\">$TITLE</a> @ $(date) <a href="javascript:\(function\(\)\{%20window.open\(\'http://`getip`/cgi-bin/show?$QUERY_STRING\'\)\;\}\)\(\)\;">Show</a>" | cat - $HISTORY_FILE > $TMP_HISTORY && mv $TMP_HISTORY $HISTORY_FILE 

}

function play() {
CSV="`getCliveCSV "$1"`"

if [ -n "$CSV" ]; then
  playVideoFromCSV "$CSV"
else
  notify "failed"
fi

}

function playB() {
ALL=
for line in $1; do
  CSV="`getCliveCSV "$line"`"
  ALL="$ALL `echo $CSV |cut -d'"' -f6`"
done
  if [ -n "$ALL" ]; then
    notify "playing"
    mplayer.playlist "$ALL"
  else
    notify "failed"
  fi
}

#if [ -n "`echo "$QUERY_STRING" | fgrep "list="`" ]; then
#  notify "loading youtube playlist.." 8
#  urls="`clivescan -an "$QUERY_STRING" | grep "^fetch" | awk '{ print $2 }'`" 
#  playB "`echo $urls | sed 's/ /\n/g' | sed '1d'`"
#else
 play "$QUERY_STRING"
#fi
) &> /dev/null
