#!/bin/bash
function errex(){ echo "$1"; exit; };

[ $# != 1 ] && errex "Usage: input <name>"

ARG="$1"
echo -n "<?xml version=\"1.0\"?><YAMAHA_AV cmd=\"PUT\"><Main_Zone><Volume><Lvl><Val>$ARG</Val><Exp>1</Exp><Unit>dB</Unit></Lvl></Volume></Main_Zone></YAMAHA_AV>" | unix2dos
