#!/bin/bash
. /var/www/cgi-bin/initrequest "text/html"
. ./link/functions

[ -z "$QUERY_STRING" ] && QUERY_STRING="$1";
TERMS="`prepareTerms "$QUERY_STRING"`"

locate -i -q "*$TERMS*" | while read line; do 
  title=`basename "$line"`; 
  echo "<br/><a href=\"http://10.20.30.51/cgi-bin/show?$line\">$title</a>"; 
done

