#!/bin/bash
. /var/www/cgi-bin/initrequest "text/html"
. ./link/functions

MUSIC_EXT="aac ac3 acm aif aifc aiff alac alaw amf amr ams ams  atrac au aud au cda cdda cdr flac gsm iff m3u m4a m4b mid midi mp1 mp2 mp3 mpa oga og pcm  pls r1m ra ram raw rmf rmi rmj rmm rmx sid snd sppack spx ulaw wav wave wma"

[ -z "$QUERY_STRING" ] && QUERY_STRING="$@";
TERMS="`prepareTerms "$QUERY_STRING"`"
LOCATEARGS=`makeLocateArgs "$TERMS" $MUSIC_EXT`

bash -c "locate $LOCATEARGS" | while read line; do
  title=`basename "$line"`; 
  echo "<br/><a href=\"http://10.20.30.51/cgi-bin/show?$line\">$title</a>"; 
done

