#!/bin/bash
. /var/www/cgi-bin/initrequest "text/html"
. ./link/functions

MOVIE_EXT="mpeg mpg mpe mpeg mls mpa mp2 m2a mp2v m2v m2s avi apple mov qt asf asx wma wmv wmx rm ra ram rmvb mp4 3gp ogm mkv"

[ -z "$QUERY_STRING" ] && QUERY_STRING="$@";
TERMS="`prepareTerms "$QUERY_STRING"`"
LOCATEARGS=`makeLocateArgs "$TERMS" $MOVIE_EXT`

bash -c "locate $LOCATEARGS" | while read line; do
  title=`basename "$line"`;
  echo "<br/><a href=\"http://10.20.30.51/cgi-bin/link/playlink?$title\">$line</a>";
done
