#!/bin/bash

function prepareTerms() {
  echo "$@" | sed 's/%20/ /g' | sed 's/ /\*/g'
}

function makeLocateArgs() {
  terms="$1"
  shift;
  echo -en "-d /home/lounge/link.db -q -i ";
  for ext in $@; do
    echo -en "\"*$terms*$ext\" "
  done
}
