#!/bin/bash
. /var/www/cgi-bin/initrequest "text/html"
. ./link/functions

MEDIA_EXT="svg mp3 avi mpeg mpg mov wmv mp4 3gp ogm mkv jpg jpeg gif png"


[ -z "$QUERY_STRING" ] && QUERY_STRING="$@";
TERMS="`prepareTerms "$QUERY_STRING"`"
LOCATEARGS="`makeLocateArgs "$TERMS" $MEDIA_EXT`"

locate="locate $LOCATEARGS"

FILE="`bash -c "$locate" | while read line; do if [ -f "$line" ]; then echo $line; break; fi; done`"
QUERY_STRING="$FILE"
./show "$FILE"

