#!/bin/bash

. /var/www/cgi-bin/initrequest "text/html"

#mplayerproc=`ps -ef | grep mplayer | tr -s " " | cut -d" " -f8-`
midori -c /home/lounge/midori_mpdstat/ --class="MPDstat" --name="MPDstat" -e ZoomNormal

QUERY_STRING=`screen/isBeamermode | sed '1,2d'`
echo $QUERY_STRING
if [ "$QUERY_STRING" == "false" ]; then
  midori -c /home/lounge/midori_mpdstat/ --class="MPDstat" --name="MPDstat" -e ZoomOut
  midori -c /home/lounge/midori_mpdstat/ --class="MPDstat" --name="MPDstat" -e ZoomOut
  midori -c /home/lounge/midori_mpdstat/ --class="MPDstat" --name="MPDstat" -e ZoomOut
  midori -c /home/lounge/midori_mpdstat/ --class="MPDstat" --name="MPDstat" -e ZoomOut
  xrandr --auto --output VGA-0 --mode 1024x768
  xset s 10800
  xset dpms 10800 0 0
  ./off
  ./on
  screen/setBlank true
else
  xset s 90
  xset dpms 90 0 0
  xrandr --auto --output VGA-0 --mode custom
  screen/setBlank true
  sleep 3
fi

#[ -n "$mplayerproc" ] && `killall mplayer; $mplayerproc`;
screen/setBlank false

