#!/bin/bash
#
# ScreenInvader - A shared media experience. Instant and seamless.
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

FUNCTION="$1"

. /lounge/triggers/functions.sh

declare -A DATA="$(janosh get /display/.)"
l_log $@

function setResolution () {
  export DISPLAY=:0
  res="`janosh -r get /display/resolution/value`"
  xrandr --output default --mode $res
  width="`echo $res | cut -d"x" -f1`"
  height="`echo $res | cut -d"x" -f2`"
  mkdir -p /lounge/.config/midori/
  /lounge/triggers/templates/midori_config $width $height > /lounge/.config/midori/config
}

function setBlank() {
  if [ "${DATA["/display/blank"]}" == "true" ]; then
    xset dpms force standby
  else
    xset s reset
    xset dpms force on
  fi
}

function readBlank() {
  xset -q | fgrep 'Monitor is On' && echo false || echo true
}

function reload() {
  janosh set /display/blank $(readBlank)
}

function restart() {
  return 0
}

if [ "$(type -t "$FUNCTION")" == "function" ]; then
  $FUNCTION
else
  echo "Unknown command: $FUNCTION" 1>&2
  exit 1
fi


