#!/bin/bash

. /lounge/triggers/env

FUNCTION="$1"
declare -A DATA="$(janosh /network/.)"

function readWirelessNic() {
  cat /proc/net/wireless | grep -Po '^ \K([A-Za-z0-9]*)(?=:)'
}

function readWiredNic() {
  cat /proc/net/dev | grep -Po '^\s*\K(e[A-Za-z0-9]*)(?=:)'
}

function reload() {
  return 0
}

if [ "$(type -t "$FUNCTION")" == "function" ]; then
  $FUNCTION
else
  echo "Unknown command: $FUNCTION" 1>&2
  exit 1
fi


