#!/bin/bash
#
# ScreenInvader - A shared media experience. Instant and seamless.
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
. /lounge/triggers/functions.sh
l_log $@

FUNCTION="$1"
declare -A OBJ="$(janosh get /radio/.)"

function open() {
  url="${OBJ[/radio/url]}"
  l_unblank
  l_notify "Loading playlist $(basename "$url")" 1

  wget -q -O - "$url" |  tr -d '\r' | while read line; do
    player playlistEnqueue "$(l_urldecode "$line")" "" "$url"
  done
}

if [ "$(type -t "$FUNCTION")" == "function" ]; then
  $FUNCTION
else
  echo "Unknown command: $FUNCTION" 1>&2
  exit 1
fi

