#!/bin/bash
#
# ScreenInvader - A shared media experience. Instant and seamless.
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#


function isBlank() {
  [ -n "`xset -q | fgrep 'Monitor is On'`" ] && echo false || echo true
}

function setBlank() {
  if [ "$1" == "true" ]; then
    xset dpms force standby
  else
    xset s reset
    xset dpms force on
  fi
}

function toggleBlank() {
if [ $(isBlank) == "true" ]; then
  screen/setBlank false
else
  screen/setBlank true
  fi
}

CALL=

while getopts 'c:' c
do
  case $c in
    c) CALL="$OPTARG";;
  esac
done

shift $(($OPTIND - 1))

declare -A ARGS="$@"

blank=${ARGS["/screen/blank"]}
[ -n "$blank" ] && setBlank "$blank"
[ -n "$CALL" ] && $CALL

