#!/bin/bash

FUNCTION="$1"
declare -A DATA="$(janosh /storage/.)"

function makeSmb() {
  user="${DATA[/storage/smb/user]}"
  pass="${DATA[/storage/smb/password]}"
  domain="${DATA[/storage/smb/domain]}"
  host="${DATA[/storage/smb/host]}"
  dir="${DATA[/storage/smb/directory]}"

  cat > /etc/auto.smb <<EOSMBCONF
$host$dir      -fstype=cifs,users,user=$user,password=$pass,domain=$domain,ro ://$host/$dir
EOSMBCONF
}

function reload() {
  /etc/init.d/autofs restart
}

if [ "$(type -t "$FUNCTION")" == "function" ]; then
  $FUNCTION
else
  echo "Unknown command: $FUNCTION" 1>&2
  exit 1
fi


