#!/bin/bash

CALL=

while getopts 'c:' c
do
  case $c in
    c) CALL="$OPTARG";;
  esac
done

shift $(($OPTIND - 1))

declare -A ARGS="$@"

function makeSmb() {
  USER="${ARGS[/storage/smb/user]}"
  PASS="${ARGS[/storage/smb/password]}"
  DOMAIN="${ARGS[/storage/smb/domain]}"
  HOST="${ARGS[/storage/smb/host]}"
  DIR="${ARGS[/storage/smb/directory]}"

  cat > /etc/auto.smb <<EOSMBCONF
$HOST$DIR      -fstype=cifs,users,user=$USER,password=$PASS,domain=$DOMAIN,ro ://$HOST/$DIR
EOSMBCONF
}

[ -n "$CALL" ] && $CALL

