#!/bin/bash
#
# ScreenInvader - A shared media experience. Instant and seamless.
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. /lounge/triggers/functions.sh
l_log $@

FUNCTION="$1"

function makeInittab() {
  cat > /etc/inittab <<EOINITTAB
id:2:initdefault:
si::sysinit:/etc/init.d/rcS
~~:S:wait:/sbin/sulogin
l0:0:wait:/etc/init.d/rc 0
l1:1:wait:/etc/init.d/rc 1
l2:2:wait:/etc/init.d/rc 2
l3:3:wait:/etc/init.d/rc 3
l4:4:wait:/etc/init.d/rc 4
l5:5:wait:/etc/init.d/rc 5
l6:6:wait:/etc/init.d/rc 6
z6:6:respawn:/sbin/sulogin
ca:12345:ctrlaltdel:/sbin/shutdown -t1 -a -r now
pf::powerwait:/etc/init.d/powerfail start
pn::powerfailnow:/etc/init.d/powerfail now
po::powerokwait:/etc/init.d/powerfail stop
1:23:respawn:/sbin/getty 38400 tty1
2:23:respawn:/sbin/getty 38400 tty2
3:23:respawn:/sbin/getty 38400 tty3
4:23:respawn:/sbin/getty 38400 tty4
5:23:respawn:/sbin/getty 38400 tty5
6:23:respawn:/sbin/getty 38400 tty6
EOINITTAB
}

function emergencyReset() {
  /etc/init.d/xserver stop
  rm /lounge/janosh.db
  sudo -u lounge "janosh load /lounge/lounge.json"
  /etc/init.d/xserver start
}

function showip () {
  jrget="janosh -r get"

  if [ "$($jrget /animation/active)" == "true" -o "$($jrget /browser/active)" == "true" -o "$($jrget /image/active)" == "true" -o "$($jrget /pdf/active)" == "true" -o "$($jrget /player/active)" == "true" -o "$($jrget /radio/active)" == "true" ]; then
    killall showip
    killall osd
  else
    killall showip
    killall osd
    /lounge/bin/showip &
    /lounge/bin/player refresh   
  fi
}

function reload() {
  return 0
}

function restart() {
  return 0
}


if [ "$(type -t "$FUNCTION")" == "function" ]; then
  $FUNCTION
else
  echo "Unknown command: $FUNCTION" 1>&2
  exit 1
fi

