#!/bin/bash

. ./initcgi "text/plain"
export PATH=$PATH:/lounge/bin/locate/

[ "`janosh /media/updating`" == "true" ] && exit 0;

janosh -s /media/updating true
updatemovie
updateimage
janosh -s /media/updating false


