#!/bin/sh

### BEGIN INIT INFO
# Provides:          janosh-lounge
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts janosh for user lounge
# Description:
### END INIT INFO

export USER=lounge
export HOME=/lounge
DAEMON="/bin/bash /usr/bin/janosh-lounge"
DESC="lounge instance"
NAME=janosh
PIDFILE=/tmp/janosh-lounge.pid

set -e

case "$1" in
        start)
                echo -n "Starting $DESC: "
                start-stop-daemon -m -b -S -p $PIDFILE -x $DAEMON --oknodo -- $OPTIONS
                echo "$NAME."
                ;;

        stop)
                echo -n "Stopping $DESC: "
                start-stop-daemon -K -q -p $PIDFILE -x $DAEMON --oknodo --signal 10
                echo "$NAME."
                ;;

        force-stop)
                echo -n "Stopping $DESC: "
                start-stop-daemon -K -q -p $PIDFILE -x $DAEMON
                echo "$NAME."
                ;;

        force-reload)
                if start-stop-daemon -K -q -p $PIDFILE -x $DAEMON --test
                then
                        $0 restart
                fi
                ;;

        restart)
                $0 stop
                sleep 1
                $0 start
                ;;

        *)
                N=/etc/init.d/$NAME
                echo "Usage: $N {start|stop|force-stop|restart|force-reload}" >&2
                exit 1
                ;;
esac

exit 0
