#!/bin/bash

echo | ./catosd <<EOF
I am the mighty ScreenInvader


You connected me to your screen.


I will serve this screen well.





You need a digital device with a web browser,
To tell me what to show on screen.
EOF
