#!/bin/bash



cat osdfifo | while read line; do
  len=${#line}
  timeout=$[ $len / 10 ]
  [ $timeout -eq 0 ] && timeout=1
 echo $timeout
  ./osd -v2 -t$timeout -h1 -b230 -clightgreen -f"-misc-topaz a500a1000a2000-medium-r-normal--0-200-0-0-c-0-iso8859-1" "`echo "$line" | sed 's/-/\\-/g'`´"
done 
