#!/bin/bash
#
# ScreenInvader - A content centered media center
# Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#                    Bernd Forstner <red667@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

client_id="2dcf4e12afd6ed5119741f888260fc85"

url="$1"

json=$(curl -L "http://api.soundcloud.com/resolve.json?url=$url&client_id=$client_id")

stream=$(echo "$json" | grep -Po 'stream_url":"\K.*?(?="|$)' \
	                  | sed -e 's/https\:/http\:/')
artist=$(echo "$json" | grep -Po 'username":"\K.*?(?="|$)' | head -n1)
title=$(echo "$json" | grep -Po 'title":"\K.*?(?="|$)' | tail -n1)

echo "${stream}" | xargs -n1 -Ibla echo bla?client_id=${client_id}
echo "$artist - $title"
