#!/bin/bash
#
# ScreenInvader - A content centered media center
# Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#                    Benjamin Schwarz <pwnicorndev@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

wget -qO- $(sed 's|/listen/|/dl/|g' <<< $1) | sed -n 's|.*c = "\(.*\)/\[t.*|http://tindeck.com\1|p'
wget -qO- $(sed 's|/dl/|/listen/|g' <<< $1) | sed -n 's|.*e>\(.*\) - Tindeck.*|\1|p'

