#!/bin/bash
#
# ScreenInvader - A shared media experience. Instant and seamless.
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. /lounge/triggers/functions.sh
function parse_query() {

  IFS="&"
  KEY=$2
  array=($@)

  for i in "${array[@]}";
    do IFS="=";
    set -- $i;
    #PARAMS[$1]=$2;
    if [ "$1" == "$KEY" ]
    then
      echo $2
      return 0
    fi
  done

}

ID="`echo "$1" | sed 's/.*v=//g' | sed 's/&.*$//g'`"
INFO=$(wget -qO- "http://www.youtube.com/get_video_info?&video_id=$ID&el=detailpage")
STREAMS=$(l_urldecode "`parse_query $INFO "url_encoded_fmt_stream_map"`")
TITLE=$(l_urldecode "`parse_query $INFO "title"`")
IFS=","
set -- $STREAMS
for SQUERY in $@; do
  QUALITY=`parse_query $SQUERY "quality"`
  FORMAT=$(l_urldecode "`parse_query $SQUERY "type"`"|cut -d ';' -f1)
  #if [ "$QUALITY" == "large" -a "$FORMAT" != "video/x-flv" ];
  if [ "$FORMAT" != "video/x-flv" ];
  then
    SURL=$(l_urldecode "`parse_query $SQUERY "url"`")
    SIG="`parse_query $SQUERY "sig"`"
    URL="$SURL&signature=$SIG"
    break
  fi
done

echo $URL
echo $TITLE
