#!/bin/bash

. /lounge/bin/initcgi "text/plain"

function postInput() {
 cat "/lounge/www/cgi-bin/requests/$1" | ./post &> /dev/null
}

 case $1 in
    1 )
      postInput "AUDIO1"
      /lounge/www/cgi-bin/screen/toggleBeamermode
    ;;
    2 )
      postInput "AUDIO2"
    ;;
    3 )
      postInput "AV5"
      /lounge/www/cgi-bin/screen/setBlank true
    ;;
    4 )
      postInput "AV6"
      /lounge/www/cgi-bin/screen/setBlank true
    ;;
    5 ) 
      postInput "Bluetooth"
      /lounge/www/cgi-bin/screen/setBlank true
    ;;
    6)
      postInput "USB"
    ;;
    7)
      postInput "V-AUX"
      /lounge/www/cgi-bin/screen/setBlank true
    ;;

esac


