#!/bin/bash

. ./initrequest "text/html"

#mplayerproc=`ps -ef | grep mplayer | tr -s " " | cut -d" " -f8-`
midori -c /home/lounge/midori_mpdstat/ --class="MPDstat" --name="MPDstat" -e ZoomNormal

QUERY_STRING=$1
if [ "$QUERY_STRING" != "OFF" -a "$QUERY_STRING" != "off" ]; then
  midori -c /home/lounge/midori_mpdstat/ --class="MPDstat" --name="MPDstat" -e ZoomOut
  midori -c /home/lounge/midori_mpdstat/ --class="MPDstat" --name="MPDstat" -e ZoomOut
  midori -c /home/lounge/midori_mpdstat/ --class="MPDstat" --name="MPDstat" -e ZoomOut
  midori -c /home/lounge/midori_mpdstat/ --class="MPDstat" --name="MPDstat" -e ZoomOut
  xrandr --auto --output VGA-0 --rate 60 --mode 1024x768
  xset s 10800
  xset dpms 10800 0 0
  ./off
  ./on
else
  xset s 90
  xset dpms 90 0 0
  xrandr --auto --output VGA-0 --mode custom
fi

#[ -n "$mplayerproc" ] && `killall mplayer; $mplayerproc`;
./unblank

