#!/bin/bash

. ./initrequest "text/html"

#mplayerproc=`ps -ef | grep mplayer | tr -s " " | cut -d" " -f8-`

QUERY_STRING=$1
if [ "$QUERY_STRING" != "OFF" -a "$QUERY_STRING" != "off" ]; then
  xrandr --auto --output VGA-0 --rate 60 --mode 1024x768
  xset s 10800
  xset dpms 10800 10800 0
  ./off
  ./on
else
  xset s 90
  xset dpms 90 90 0
  xrandr --auto --output VGA-0 --mode custom
fi

#[ -n "$mplayerproc" ] && `killall mplayer; $mplayerproc`;
./unblank

