#!/bin/bash
. ./initrequest "text/html"

./clean


[ -z "$QUERY_STRING" ] && QUERY_STRING=$1;
pid=`ps -ef | grep "midori.*class=Browser" | fgrep -v grep | tr -s " " | cut -d" " -f2`
if [ -n "$pid" ]; then 
	midori --class="Browser" --name="Browser" -e TabCloseOther 
fi
midori --class="Browser" --name="Browser" $QUERY_STRING &> /dev/null
