#!/bin/bash
export DISPLAY=:0
echo Content-type: text/html
echo ""

killall -9 mplayer
./unblank

./startmidori

midori --class="Browser" --name="Browser" -e TabCloseOther
midori --class="Browser" --name="Browser" $QUERY_STRING & disown
midori --class="Browser" --name="Browser" -e TabCloseOther
