#!/bin/bash

. ./initrequest "text/plain"

killall -9 mplayer.orig
killall -9 mplayer
killall -9 feh
pid=`ps -ef | grep "midori.*class=Browser" | fgrep -v grep | tr -s " " | cut -d" " -f2`
[ -n "$pid" ] && kill -9 $pid
echo ho
