#!/bin/bash
temp=`curl --silent "http://xml.weather.yahoo.com/forecastrss?p=AUXX0025&u=c" | grep Current -A 1 | sed -e 's/<br \/>//' -e 's/<b.*>//' -e 's/ C<BR \/>//' | cut -d , -f 2 | cut -c 2- | tr -d '\n'` 
prog=`curl --silent "http://wetter.orf.at/wien/" | grep "<h1>" | sed -e 's/\<h1\>//' -e 's/\<\/h1\>//' -e 's/^[[:space:]]*//'`
date=`date "+%d.%m % - %H:%M"`
echo -e "\n\tDatum:      "`date '+%A'/``if which ddate > /dev/null; then ddate | cut -f 3 -d ' ' | cut -f 1 -d ,; fi`", $date"
echo -e "\tTemperatur: ""$temp""°C"
echo -e "\tWetter:     ""$prog""\n"