#!/bin/bash
. ./initrequest "text/html"

./unblank

TERMS="`echo $QUERY_STRING | sed 's/%20/ /g'`"

find /link/Media/Series -type f -iname "*$TERNS*.mp4" -o -iname "*$TERMS*.avi" -o -iname "*$TERMS*.mov" -o -iname "*$TERMS*.mpg"  -o -iname "*$TERMS*.mpeg"  -o -iname "*$TERMS*.mkv" -o -iname "*$TERMS*.flv" | while read line; do filename=`basename "$line"`; title=${filename%.avi}; echo "<br/><a href=\"http://10.20.30.51/cgi-bin/playlink?$title\">$line</a>"; done

