#!/bin/bash
. ./initrequest "text/html"

./unblank

mpc -q pause &> /dev/null
TERMS="`echo $QUERY_STRING | sed 's/%20/ /g'`"

find /link/Media/ -type f -iname "*$TERMS*.mp3" -o  -iname "*$TERMS*.ogg" -o  -iname "*$TERMS*.flac" -o -iname "*$TERMS*.avi" -o -iname "*$TERMS*.mov" -o -iname "*$TERMS*.mpg"  -o -iname "*$TERMS*.mpeg"  -o -iname "*$TERMS*.mkv" -o -iname "*$TERMS*.flv" | while read line; do filename=`basename "$line"`; title=${filename%.avi}; echo "<br/><a href=\"http://10.20.30.51/cgi-bin/playlink?$title\">$line</a>"; done

