#!/bin/bash

. ./initrequest "text/html"

export HOME=/home/lounge

./clean
./unblank

feh -g"`./getGeometry`" --image-bg black --auto-zoom "$QUERY_STRING" &> /dev/null &
disown &> /dev/null
echo "`date` $QUERY_STRING" >> log/image.log

exit 0
