#!/bin/bash
. ./initrequest "text/html"

./clean
./unblank

mpc -q pause &> /dev/null
TERMS="`echo $QUERY_STRING | sed 's/%20/ /g' | sed 's/ /\*/g'`"
echo "QUERY_STRING $TERMS"

FILE="`find /link/Media/Series /link/Media/Film -type f -iname "*$TERMS*" | sed '1q'`"

mplayer -fs "$FILE" &> /dev/null

