#!/bin/bash
. ./initrequest "text/html"

./clean
./unblank

mpc -q pause &> /dev/null
TERMS="`echo $QUERY_STRING | tr " " "*"`"
FILE="`find /link/Media/ -type f -iname "*$TERMS*.avi" -o -iname "*$TERMS*.mov" -o -iname "*$TERMS*.mpg"  -o -iname "*$TERMS*.mpeg"  -o -iname "*$TERMS*.mkv" -o -iname "*$TERMS*.flv" | sed '1q'`"

mplayer -fs "$FILE" &> /dev/null

