#!/bin/bash
. /var/www/cgi-bin/initrequest "text/html"

./clean &> /dev/null

function getHead() {
  HEAD=
  LOCATION="$1"
  while [ -n "$LOCATION" ]; do
    HEAD="`curl -L -m1 -s -i -X HEAD \"$LOCATION\"`"
    LOCATION="`echo "$HEAD" | fgrep "Location: " | cut -d" " -f2 | dos2unix`"
  done
  echo "$HEAD" | dos2unix
}

function isFileType() {
  if [ -n "`echo "$1" | fgrep -i "$2"`" ]; then
    return 0
  else
    return 1
  fi
}

[ -z "$QUERY_STRING" ] && QUERY_STRING="$@";

if [ -z "`echo "$QUERY_STRING" | grep "^http"`" ]; then
  FILE="`echo -e "$QUERY_STRING" | echo -e $(sed 's/%/\\\x/g')`"
  echo "FILE $FILE</br>"
  FILEINFO="`file "$FILE"`"
  echo "INFO $FILEINFO</br>"

  QUERY_STRING="$FILE"
  if isFileType "$FILEINFO" "audio"; then
    ./video "$QUERY_STRING"
  elif isFileType "$FILEINFO" "video"; then
   ./video "$QUERY_STRING"
  elif isFileType "$FILEINFO" "image"; then
    ./image "$QUERY_STRING"
  else
    ./video "$QUERY_STRING"
  fi
 
  exit
fi

if [ -z "`echo "$QUERY_STRING" | fgrep "youtube.com/watch"`" ]; then
  HEAD=`getHead "$QUERY_STRING"`
  LOCATION="$QUERY_STRING";
  CONTENT_TYPE="`echo "$HEAD" | fgrep "Content-Type: " | cut -d" " -f2;`"
  
  [ -z "$CONTENT_TYPE" ] && CONTENT_TYPE="text/html";

  CATEGORY="`echo "$CONTENT_TYPE" | cut -d"/" -f1;`"

  echo $CATEGORY
  QUERY_STRING="$LOCATION"
  case "$CATEGORY" in
    "image" )
      ./image "$LOCATION"
    ;;
    "video" )
      ./video "$LOCATION"
    ;;
    "text" )
      ./browse "$LOCATION"
    ;;
  esac
else
  ./youtube "$QUERY_STRING"
fi

