#!/bin/bash
. ./initrequest "text/html"

./clean
./unblank


pid=`ps -ef | grep "midori.*class=Browser" | fgrep -v grep | tr -s " " | cut -d" " -f2`
if [ -n "$pid" ]; then
        midori --class="Browser" --name="Browser" -e TabCloseOther
fi
midori --class="Browser" --name="Browser" http://10.20.30.51/lyrics.html &> /dev/null
