#!/bin/bash

. ./initrequest "text/html"

./unblank

COOKIE_FILE=/var/tmp/youtube-dl-cookies.txt
mplayer -fs -cookies -cookies-file "${COOKIE_FILE}" "$(youtube-dl -g -f18 --cookies ${COOKIE_FILE} "$QUERY_STRING")" &> /dev/null &
disown

