#!/bin/bash
#
# ScreenInvader - A shared media experience. Instant and seamless.
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

export DISPLAY=:0
export HOME=/lounge
export PATH="$HOME/bin:/lounge/www/cgi-bin/:$PATH"
export LOGDIR="/var/log/lounge"

echo "Content-type: $1"
echo ""
cd $HOME/www/cgi-bin/

function l_urldecode() {
  echo $1 | sed -e's/%\([0-9A-F][0-9A-F]\)/\\\\\x\1/g' | xargs echo -e | sed 's/+/ /g'
}

function l_unblank() {
  xdotool mousemove 1900 1200
  janosh -t -s /display/blank false
}

function l_lock() {
  lockname="$1"
  cat | (
  flock -n 200 | exit 111
  cat
  ) 200> "/var/lock/$lockname" &> /dev/null
}

function l_notify() {
  timeout=$2
  [ -z "$timeout" ] && timeout=2

  arg="$1"
  title=${arg:0:48}
  killall osd
  /lounge/bin/osd -t "$timeout" "$title" &
}
export -f l_unblank l_notify
