#!/bin/bash
#
# ScreenInvader - A shared media experience. Instant and seamless.
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#


set -x
. /lounge/bin/initcgi "text/html"

#./reset

notify "Loading orf..."

[ -z "$QUERY_STRING" ] && QUERY_STRING="$@"

(
function playUrl() {
  player loadVideo "$1" "orf stream"
  disown
}

MMS_URL="`orfget.sh "$QUERY_STRING"`"

if [ -n "$MMS_URL" ]; then 
  playUrl "$MMS_URL"
else
  notify "failed"
fi
)
# &> /dev/null
