#!/bin/bash
#
# ScreenInvader - A shared media experience. Instant and seamless.
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#



. ./initcgi "text/html"
(
  flock -x 200
  CACHE="/var/run/player/playlist_cache"
  LAST="`cat /var/run/player/playlist_last`"
  [ -z "$LAST" ] && LAST=0
  mod_c="`stat -c %Y $CACHE`"
  SIZE=$(janosh size /playlist/items/. 2> /dev/null)
  if [ $mod_c -gt $LAST ]; then
    if [ $SIZE  -eq 0 ]; then
      echo "<span style=\"color: lightgrey; font-weight: bold;\">(playlist empty)</span>" > "$CACHE"
    else
      (
      echo "<ul id='playlist' style=\"margin:0; padding: 5; border: 5px; border-radius: 9px; background-color: inherit; \">"
      i=0
      
      seq 0 $[ $SIZE - 1 ] | while read index; do
        title="$(janosh -r get /playlist/items/#${index}/title 2> /dev/null)"
        title="`echo $title | sed -e 's/\([A-Z]\)/\1/g' -e 's/^ \([a-z]\)/\1/g'`"
        title=${title:0:70}
        class=
        idx="$(janosh -r get /playlist/index 2> /dev/null)"
        color="white"
        bgcolor="#555"
        id="$i"
	
        [ $[ $i % 2  ] -eq 0 ] && bgcolor="#777"
        if [ "$i" -eq "$idx" ]; then 
          color="orange"
          class="currentItem"
        fi
        echo "\
<li id=\"$id\" style=\"width: 100%; margin: 0; padding: 2px;text-align:left; cursor: pointer; background-color: $bgcolor; color: $color;  border: 1px outset $bgcolor; font-size: 12px; list-style-type: none; \" class=\"$class\">\
<table style=\"border:0; padding:0; margin:0; border-radius: 0; background-color: inherit;\">\
<tr style=\"padding: 0; margin: 0; border: 0; border-radius: 0;\"><td style=\"width: 100%; padding: 0; margin: 0; border: 0; border-radius: 0;\" onclick=\"$.get('cgi-bin/playlist_jump?$i');\">$title</td>\
<td onclick=\"$.get('cgi-bin/playlist_remove?$i');\" style=\"padding: 1px 6px 1px 6px; margin: 0; border: 1px outset $bgcolor; border-radius: 0; \" class=\"button up\">X</td></tr></table></li>"
        i=$[ $i + 1 ]
      done
      
      echo "</ul>"
      ) > "$CACHE"
      stat -c %Y /var/run/player/playlist_cache > /var/run/player/playlist_last
    fi
  fi

  cat "$CACHE"
) 200> /var/lock/playlist
