#!/bin/bash
#
# ScreenInvader - A shared media experience. Instant and seamless.
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

echo "Content-type: text/html"
echo ""

(
set -x
declare -A VIDEO_HOSTS="( \
[youtube.com/]='youtube' \
[tvthek.orf.at/]='orf' \
[videos.arte.tv/]='arte7' \
[vimeo.com/]='vimeo' \
[soundcloud.com/]='soundcloud' \
[soup.io/post]='soup' \
)"

declare -A CATEGORY_MAP="( \
[video]='./video' \
[audio]='./video' \
[image]='./image' \
[animation]='./animation' \
[radio]='./radio' \
[text]='./browse' \
[pdf]='./pdf' \
[youtube]='./youtube' \
[orf]='./orf' \
[arte7]='./arte7' \
[vimeo]='./vimeo' \
[soundcloud]='./soundcloud' \
[soup]='./soup' \
)"

declare -A CATEGORY_FIX="( \
[application/x-matroska]='video' \
[application/pls]='radio' \
[application/pdf]='pdf' \
[audio/x-scpls]='radio' \
[image/gif]='animation'
)"

function getCategory() {
  url="$1"
  for host in "${!VIDEO_HOSTS[@]}"
  do
    if [[ $url =~ http[s]*://.*$host ]]; then
      echo "${VIDEO_HOSTS[$host]}"
      return
    fi
  done

  mime_type="unknown/"

  if [[ $url =~ http[s]*:// ]]; then
    head=
    location="$url"
    while [ -n "$location" ]; do
      head="$( curl --head "$location" | dos2unix )"
      location="$( echo "$head" | grep -Po 'Location: \K(.*)?(?=)' )"
    done
    mime_type="$( echo "$head" | grep -Po 'Content-Type: \K(.*)?(?=)' )"
  elif  [[ $( readlink -e "$url" ) == /share/* ]]; then
    file=$( l_urldecode "$url" )
    mime_type=$( file -i "$file" | sed 's/.*: \([a-zA-Z]*\/[a-zA-Z]*\).*/\1/p' )
  fi

  category="${CATEGORY_FIX[$mime_type]}"
  if [ -z "$category" ]; then
    category="$( echo "$mime_type" | cut -d"/" -f1 )"
  fi
  echo "$category"
}

/lounge/www/cgi-bin/handlers/${CATEGORY_MAP["$(getCategory "$QUERY_STRING")"]}
) &>/dev/null &

cat /lounge/www/close.html

