#!/bin/bash
#
# ScreenInvader - A shared media experience. Instant and seamless.
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
. ./initcgi "text/html"

(
declare -A VIDEO_HOSTS="( \
[youtube.com/]='youtube' \
[youtu.be/]='youtube' \
[tvthek.orf.at/]='orf' \
[videos.arte.tv/]='arte7' \
[vimeo.com/]='vimeo' \
[soundcloud.com/]='soundcloud' \
[ted.com/]='ted' \
)"

declare -A CATEGORY_MAP="( \
[video]='player' \
[audio]='player' \
[image]='browser' \
[animation]='browser' \
[radio]='radio' \
[text]='browser' \
[pdf]='pdf' \
[youtube]='player' \
[orf]='player' \
[arte7]='player' \
[vimeo]='player' \
[soundcloud]='player' \
[ted]='player' \
)"

declare -A CATEGORY_FIX="( \
[application/x-matroska]='video' \
[audio/x-mpegurl]='radio' \
[application/pls]='radio' \
[application/pdf]='pdf' \
[audio/x-scpls]='radio' \
[image/gif]='animation' \
)"

function getCategory() {
 set -x
  url="$1"
  for host in "${!VIDEO_HOSTS[@]}"
  do
    if [[ $url =~ http[s]*://.*$host ]]; then
      echo "${VIDEO_HOSTS[$host]}"
      return
    fi
  done

  mime_type="unknown/"

  if [[ $url =~ http[s]*:// ]]; then
    head=
    location="$url"
    while [ -n "$location" ]; do
      head="$( curl --head "$location" | dos2unix )"
      location="$( echo "$head" | grep -iPo 'Location: \K(.*)?(?=)' )"
    done
    mime_type="$( echo "$head" | grep -iPo 'Content-Type: \K(.*)?(?=)' )"
  elif  [[ $( readlink -e "$url" ) == /tmp/* ]]; then
    file="$url"
    mime_type=$( file -i "$file" | sed 's/.*: \([a-zA-Z]*\/[a-zA-Z]*\).*/\1/p' | sed '1d' )
  fi


  category="${CATEGORY_FIX[$mime_type]}"
  if [ -z "$category" ]; then
    category="$( echo "$mime_type" | cut -d"/" -f1 )"
  fi
  echo "$category"
}
url="$QUERY_STRING"
category="$(getCategory "$url")"
handler="${CATEGORY_MAP[$category]}"

[ -n "$handler" ] && /lounge/bin/janosh -t set "/$handler/url" "$url" "/$handler/category" "$category"
) &>/dev/null &

cat /lounge/www/close.html

