#!/bin/bash
#
# ScreenInvader - A shared media experience. Instant and seamless.
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ./initcgi "text/html"
./reset

/var/www/bin/notify "Loading soup..." 1

[ -z "$QUERY_STRING" ] && QUERY_STRING="$@"

function getImage() {
  echo "$1" | fgrep "click to zoom" | sed 's/^.*href="//g' | sed 's/".*$//g'
}

function getVimeo() {
  ID="`echo "$1" | grep "<embed.*vimeo.com" | sed 's/^.*clip_id=//g'  | sed 's/&.*$//g'`"
  [ -n "$ID" ] && echo "http://vimeo.com/$ID"
}

function getYoutube() {
  URL="`echo "$1" | grep "<embed.*youtube.com" | sed 's/^.*embed src="//g'  | sed 's/".*$//g'`"
  [ -n "$URL" ] && echo "$URL"
}

PAGE="`wget -q -O - "$QUERY_STRING"`"
IMAGE="`getImage "$PAGE"`"
VIMEO="`getVimeo "$PAGE"`"
YOUTUBE="`getYoutube "$PAGE"`"


[ -n "$IMAGE" ] && QUERY_STRING="$IMAGE" ./image "$IMAGE"
[ -n "$VIMEO" ] && QUERY_STRING="$VIMEO" ./youtube "$VIMEO"
[ -n "$YOUTUBE" ] && QUERY_STRING="$YOUTUBE" ./youtube "$YOUTUBE"

