#!/bin/bash
#
# ScreenInvader - A shared media experience. Instant and seamless.
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ./initcgi "text/html"
./reset

notify "Loading youtube..." 1

[ -z "$QUERY_STRING" ] && QUERY_STRING="$@"

(
function urldecode() {
  echo $1 | sed -e's/%\([0-9A-F][0-9A-F]\)/\\\\\x\1/g' | xargs echo -e | sed 's/+/ /g'
}

function selectVideo() {
  info="`echo $1 |  sed 's/%2Curl%3D/\n/g'`"
  prefered="large medium small"
  nonflv="`echo "$info" | fgrep -v video%252Fx-flv`"
  [ -n "$nonflv" ] && info="$nonflv"

  for q in $prefered; do
    quality="`echo "$info" | grep "quality%3D${q}"`"

    if [ -n "$quality" ]; then
       echo $quality
       break;
    fi
  done
}

ID="`echo $QUERY_STRING | sed 's/.*v=//g' | sed 's/&.*$//g'`"
INFO=$(wget -qO- "http://www.youtube.com/get_video_info?&video_id=$ID&el=detailpage")
SELECT="`selectVideo $INFO`"
echo "$SELECT"
TITLE=$(urldecode "`echo "$INFO" | sed -n 's/\([^&]*&\)*title=\([^&]*\).*/\2/p'`")
URL=$(urldecode "`echo "$SELECT" |  sed 's/.*url_encoded_fmt_stream_map//g' | sed 's/%26quality.*//g' | sed 's/^=url%3D//g'`")
URL=$(urldecode $URL)

player loadVideo "$URL" "$TITLE"
disown

) &> /dev/null
