#!/bin/bash

. /lounge/bin/initcgi "text/html"

QUERY_STRING=`/lounge/www/cgi-bin/screen/isBeamermode | sed '1,2d'`
  xset s 10800
  xset dpms 10800 0 0
  /lounge/www/cgi-bin/off
  sleep 1
  /lounge/www/cgi-bin/on
/lounge/www/cgi-bin/screen/setBlank false

