#!/bin/bash

. /lounge/bin/initcgi "text/plain"
if [ "`sound/isMute | sed '1,2d'`" == "true" ]; then
    cat "requests/muteoff" | ./post &> /dev/null
else
    cat "requests/muteon" | ./post &> /dev/null
fi
echo
