#!/bin/bash

. /root/triggers/env

FUNCTION="$1"
declare -A DATA="$(janosh get /network/.)"

function makeHostname() {
  echo "${DATA[/network/hostname]}" > "/etc/hostname"
}

function makeNetworkDhcp() {
  cat > /etc/network/interfaces <<EODHCPCONF
auto lo ${DATA[/network/connection/interface]}
iface lo inet loopback
allow-hotplug ${DATA[/network/connection/interface]}
iface ${DATA[/network/connection/interface]} inet dhcp
EODHCPCONF

[ "${DATA[/network/connection/value]}" == "Wifi" ] && addWifi

}

function makeNetworkMan() {
  cat > /etc/network/interfaces <<EONETCONF
auto lo ${DATA[/network/connection/interface]}
iface lo inet loopback
allow-hotplug ${DATA[/network/connection/interface]}
iface ${DATA[/network/connection/interface]} inet static
address ${DATA[/network/address]}
netmask ${DATA[/network/netmask]}
gateway ${DATA[/network/gateway]}
EONETCONF

[ "${DATA[/network/connection/value]}" == "Wifi" ] && addWifi
}

function makeNetwork() {
  if [ "${DATA[/network/mode/value]}" == "DHCP" ]; then 
    makeNetworkDhcp
  else
		makeNetworkMan
  fi
}

function makeDns() {
  cat > /etc/resolv.conf <<EORESOLVCONF
domain local
search local
nameserver ${DATA[/network/nameserver]}
EORESOLVCONF
}

function addWifi() {

enc="${DATA[/network/wifi/encryption/value]}"

cat >> /etc/network/interfaces <<EOWIFICONF
wpa-ssid ${DATA[/network/wifi/ssid]}
wpa-ap-scan 1
wpa-key-mgmt $enc
EOWIFICONF

if [ "$enc" != "NONE" ]; then
  cat >> /etc/network/interfaces <<EOPHRASE
wpa-psk ${DATA[/network/wifi/passphrase]}
EOPHRASE
fi
}

function readWirelessNics() {
  cat /proc/net/wireless | grep -Po '^ \K([A-Za-z0-9]*)(?=:)'
}

function readWiredNics() {
  cat /proc/net/dev | grep -Po '^\s*\K(e[A-Za-z0-9]*)(?=:)'
}

function readHostname() {
  cat /etc/hostname
}

function reload() {
  i=0

  janosh set /network/hostname "$(readHostname)"

  readWiredNics | while read c; do
    janosh set "/network/connection/wired/choices/#$i" "$c"
    i=$[$i+1]
  done

  readWirelessNics | while read c; do
    janosh set "/network/connection/wireless/choices/#$i" "$c"
    i=$[$i+1]
  done

  restart
  killall osd
  sudo -u lounge /lounge/bin/showip &
}

function restart() {
  readWirelessNics | xargs -Ibla -n1 ifconfig bla down
  readWiredNics | xargs -Ibla -n1 ifconfig bla down
  /etc/init.d/networking stop
  /etc/init.d/networking start
  ifup "${DATA[/network/connection/interface]}"
}

function apply() {
  makeNetwork
  makeDns
  makeHostname
  restart
}

if [ "$(type -t "$FUNCTION")" == "function" ]; then
  $FUNCTION
else
  echo "Unknown command: $FUNCTION" 1>&2
  exit 1
fi


