#!/bin/bash
. ../initcgi "text/html"
. /lounge/bin/locate/functions.sh

[ -z "$QUERY_STRING" ] && QUERY_STRING="$@";
TERMS="`prepareTerms "$QUERY_STRING"`"
LOCATEARGS=`makeLocateArgs "$TERMS"`
bash -c "locate.findutils -d /lounge/movie.db $LOCATEARGS" | while read line; do
  title=`basename "$line"`;
  echo "<br/><a href=\"http://`getip`/cgi-bin/show?$line\">$title</a>";
done
