#!/bin/bash
. /var/www/cgi-bin/initrequest "text/html"
. /lounge/bin/locatefunctions.sh

MUSIC_EXT="aac ac3 flac m4a mp3 oga wav wave wma"

[ -z "$QUERY_STRING" ] && QUERY_STRING="$@";
TERMS="`prepareTerms "$QUERY_STRING"`"
LOCATEARGS=`makeLocateArgs "$TERMS" $MUSIC_EXT`

bash -c "locate $LOCATEARGS" | while read line; do
  title=`basename "$line"`; 
  echo "<br/><a href=\"http://`getip`/cgi-bin/show?$line\">$title</a>"; 
done

