#!/bin/bash
. ../initcgi "text/html"
. /lounge/bin/locate/functions.sh

MEDIA_EXT="svg avi mpeg mpg mov wmv mp4 3gp ogm mkv jpg jpeg gif png"


[ -z "$QUERY_STRING" ] && QUERY_STRING="$@";
TERMS="`prepareTerms "$QUERY_STRING"`"
notify "Searching: $TERMS"
LOCATEARGS="`makeLocateArgs "$TERMS" $MEDIA_EXT`"
locate="locate.findutils $LOCATEARGS"
echo $locate

FILE="`bash -c "$locate" | shuf | sed '1q'`"
QUERY_STRING="$FILE"

[ -z "$FILE" ] && notify "nothing found" || player loadVideo "$FILE" "`basename $FILE`"



